language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
  - hhvm-nightly
  - nightly

matrix:
  allow_failures:
    - php: hhvm-nightly
    - php: nightly

before_script:
  - echo $TRAVIS_PHP_VERSION
  - echo $(php -r 'echo PHP_VERSION;' | grep -E '[0-9]+[.][0-9]+[.][0-9]+' -o)
  - if [[ $TRAVIS_PHP_VERSION =~ ^[0-9]+[.][0-9]+$ ]];
      then echo 'disabling XDebug';
      phpenv config-rm xdebug.ini;
      echo "memory_limit=2G" >> ~/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/conf.d/travis.ini;
      php -r 'echo ini_get("memory_limit");';
  fi
  - composer self-update
  - composerPath=`composer --help | grep 'php .*composer.* help list' | grep -Po '[^ ]+composer'`
  - php /home/travis/.phpenv/versions/$TRAVIS_PHP_VERSION/bin/composer --help
  - ( set -o posix ; set )
  - ls -al
  - ls -al /usr/bin
  - ls -al /usr/local/bin
  - chmod +x ./lets_probe.php

script:
  - ./lets_probe.php
