language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - hhvm
  - hhvm-nightly
  - nightly

matrix:
  allow_failures:
    - php: hhvm-nightly
    - php: nightly

before_script:
  - echo $TRAVIS_PHP_VERSION
  - if [[ $TRAVIS_PHP_VERSION =~ ^PHP ]]; then echo 'disabling'; phpenv config-rm xdebug.ini; fi
  - ( set -o posix ; set )

script:
  - ./lets_probe.php
