language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
  - hhvm-nightly
  - nightly

matrix:
  allow_failures:
    - php: hhvm-nightly
    - php: nightly

before_script:
  - echo $TRAVIS_PHP_VERSION
  - if [[ $TRAVIS_PHP_VERSION =~ ^[0-9]+[.][0-9]+$ ]]; then echo 'disabling'; phpenv config-rm xdebug.ini; fi
  - ( set -o posix ; set )
  - alias
  - whereis composer
  - chmod +x ./lets_probe.php

script:
  - ./lets_probe.php
